# Generated by Django 3.0.7 on 2021-12-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20211125_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcategory',
            name='category',
            field=models.CharField(default='', help_text='Kategorie (zb: Glas, Holz, Metall', max_length=200, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='unit',
            field=models.CharField(choices=[('QUADRATMETER', 'Quadratmeter'), ('LFM', 'LFM'), ('STUECK', 'Stück'), ('LITER', 'Liter')], default='QUADRATMETER', max_length=200, null=True, verbose_name='Einheit'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='width',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Breite oder Durchmesser (cm)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='import_preferences',
            field=models.TextField(choices=[('PICKUP', 'Abholung'), ('DELIVERY', 'Lieferung an Material Mafia')], default='PICKUP', max_length=9, null=True, verbose_name='Lieferpräferenzen'),
        ),
    ]
