# Generated by Django 3.0.7 on 2022-05-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20220513_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcategory',
            name='category',
            field=models.CharField(default='', help_text='Kategorie (zb: Glas, Holz, Metall', max_length=200,  verbose_name='Kategorie'),
        ),
    ]
