# Generated by Django 3.0.7 on 2022-07-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20220513_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='objekt',
            name='length',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Länge'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='category',
            field=models.CharField(default='', help_text='Kategorie (zb: Glas, Holz, Metall', max_length=200, verbose_name='Kategorie'),
        ),
    ]
